### ISSUE TITLE
Move *.tt files to the .NET Core project

### ISSUE THREAD

**Issue by bricelam** [divega/EdmxDotNetCoreSample#1]
Have you considered moving the *.tt files to the .NET Core project? This should avoid the need to link *.cs files.

**Comment by divega** [comment]
Hey Brice, I didn’t feel at the time that this would be better although there wasn’t a strong reason. But now thinking about I wonder if it would work that well. For instance, I don’t know if triggering the regeneration of the code automatically when the Edmx is saved requires the edmx file to be in the same project. A bit of a weaker reason: I believe I remember seeing item nesting didn't work well in the .NET Core project.

Anyway, it sounds like it could be worth exploring.

**Comment by bricelam** [comment]
Ah, I forgot the designer triggered the templates. It might break that.

**Comment by divega** [comment]
Whomever has a chance to try it first will let the other know :smile:
